### ISSUE TITLE
Simplest Manifest - Image

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#1]
## Simplest Manifest - Image

https://github.com/IIIF/cookbook-recipes/blob/master/cookbook/0001-mvm-image/index.md

## Use case  
The minimum viable manifest. You have an image resource on the web and want to present it using IIIF.

**Comment by mikeapp** [comment]
https://preview.iiif.io/cookbook/themed/recipe/0001-mvm-image/

**Comment by saracarl** [comment]
New title:  "Single Static Image"

**Comment by sredick** [comment]
At the top of the cookbook, what are the assumptions? That every recipe will be to build a manifest, that the purpose of every recipe will be to display and create items? Is another assumption that these are based in needs of front-end users (scholars, students, general public)? 

Target audiences for all recipes: publishers or implementers.

**Comment by sredick** [comment]
Who is "you" in the use case? does the presentation depend on a particular system, or should it be system-agnostic?

**Comment by jrgriffiniii** [comment]
The recipe has been moved to https://github.com/IIIF/cookbook-recipes/blob/master/recipe/0001-mvm-image/index.md

**Comment by triplingual** [comment]
Recipe complete at https://iiif.io/api/cookbook/recipe/0001-mvm-image/
