### ISSUE TITLE
Book (viewingDirection variations)

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#10]
## Book (viewingDirection variations)

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
I have books that read left-to-right; I have scrolls that read top to bottom.

**Comment by tomcrane** [comment]
Equivalent to 2.1 fixtures

https://iiif.io/api/presentation/2.1/example/fixtures/11/manifest.json
https://iiif.io/api/presentation/2.1/example/fixtures/12/manifest.json
https://iiif.io/api/presentation/2.1/example/fixtures/13/manifest.json
https://iiif.io/api/presentation/2.1/example/fixtures/14/manifest.json

**Comment by glenrobson** [comment]
Thanks to @kirschbombe we now have fixtures for right to left and top to bottom:

https://fixtures.iiif.io/

 * ethiopic_ms46_scroll is an top to bottom scroll
 * kabuki_ezukushi_rtl is right to left

**Comment by kirschbombe** [comment]
ethiopic_ms46_scroll is also a good example to demo "continuous" behavior :)

**Comment by triplingual** [comment]
Excellent! Thanks to both of you.

**Comment by triplingual** [comment]
@glenrobson RTL images are 403ing for me. e.g. https://fixtures.iiif.io/images/UCLA/kabuki_ezukushi_rtl/ucla_bib1987273_no001_rs_001.jpg
(Ethiopic scroll images are fine.)

**Comment by glenrobson** [comment]
Thanks @triplingual, they should be working now.
