### ISSUE TITLE
Provide API test fixtures and resources on GH Pages

### ISSUE THREAD

**Issue by christopher-johnson** [IIIF/cookbook-recipes#100]
This is a feature request.  GH pages supports CORS, so for public shared examples and tests that use these fixtures, it would be very convenient for a client to source them directly.

**Comment by stephenwf** [comment]
One thing to note, if served off of `github.io` cross-origin XHR requests to Github may be blocked by common ad-blockers (from the crypto-mining list)

**Comment by glenrobson** [comment]
For info IIIF version 1 and 2 fixtures are available with CORS on the IIIF website. For example the following fixtures:

https://github.com/IIIF/api/tree/image-prezi-rc2/source/api/presentation/2.1/example/fixtures

are accessible as:

http://iiif.io/api/presentation/2.1/example/fixtures/1/manifest.json

I believe version 3 fixtures will be on the cookbook site with CORS enabled.

**Comment by azaroth42** [comment]
Propose close -- this will happen when we have the recipes.

**Comment by glenrobson** [comment]
Do we need an activity stream to get access to the recipe manifests?

**Comment by glenrobson** [comment]
Cookbook authors agree this would be useful. Also useful as a collection. Try and automate them using jekyll.

**Comment by julsraemy** [comment]
What would also be interesting in my opinion would be te have updated information on viewer support like in the [matrix](https://iiif.io/api/cookbook/recipe/matrix/) (`yes`, `partial`, `no`).

**Comment by glenrobson** [comment]
Both the matrix and fixtures are aviliable on the cookbook website now.
