### ISSUE TITLE
Choice of Images

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#112]
## Choice of Images

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  

There are multiple images available for a given View (Canvas). For example, a painting has been photographed in 10 different wavelengths of light. The images are congruent (?) - that is, they all line up.

**Comment by azaroth42** [comment]
(Intentional) duplicate of #33; propose close ;)

**Comment by kirschbombe** [comment]
Closed as duplicate to #33 - addressed with PR #115
