### ISSUE TITLE
Add image thumbnail of resource

### ISSUE THREAD

**Issue by azaroth42** [IIIF/cookbook-recipes#117]
## Image thumbnail of Resource

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  

I want to be able to display a thumbnail image for a resource, be that a canvas, a range, an audio file or a video, such that it can be clicked to activate that particular resource.

**Comment by triplingual** [comment]
Does it matter whether this is declarative or via a service? Or should the recipe show both?

**Comment by kirschbombe** [comment]
I vote for showing both :)

**Comment by glenrobson** [comment]
We should change this one to be a manifest thumbnail and create new issue for canvas thumbnail.
