### ISSUE TITLE
Thumbnail selection algorithm implementation note

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#12]
## thumbnail algorithm / discussion

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
As a developer of client tools, how do I pick the best thumbnail for a resource?  
As a publisher, how do I help developers get the best thumbnail?

**Comment by azaroth42** [comment]
Is this a recipe or an implementation note? I think there needs to be both?

**Comment by azaroth42** [comment]
Per discussion at 2019 working session, this is the implementation note, and #117 is the recipe

**Comment by glenrobson** [comment]
Gathering background to this, notes I can find from @tomcrane:

 * [Thoughts on thumbnails](https://gist.github.com/tomcrane/8b5ba6049dc86a722632)
* [Thumbnail-Selection.md, includes auth](https://gist.github.com/tomcrane/093c6281d74b3bc8f59d)
