### ISSUE TITLE
Process: issue per use case?

### ISSUE THREAD

**Issue by azaroth42** [IIIF/cookbook-recipes#120]
The placeholder canvas idea came from AV, where "poster image" is a well known term.  However the same modeling pattern is easily applied to other scenarios, such as a journal title with many issues ... and a poster to display for the title before the issues load up.

The proposal (from the AV table) is that the journal example should be a separate issue with a separate recipe that refers back to the original model.

(This comes from #13)

**Comment by glenrobson** [comment]
Yes we agree and we have already done this with `rendering` and `start`. AV example plus a image example. 

Each recipe should be a single use case not the property. We wouldn't have two recipes for very similar use cases but we may have more than one recipe about a single property.
