### ISSUE TITLE
Process: how do we decide "ready for TRC"?

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#126]
Who puts this tag on?
And how do they know they should do that?

For example, general discussion on recipe PR and issue, multiple thumbs up - now what?

Is there a shepherd, or editor of the cookbook? Is this the spec editors' job? Keeping an eye on the issues, watching community activity on them - and stepping in when an issue looks to be ready.

The editor should make sure that contributors are getting the required feedback on their recipes in a timely fashion.

**Comment by jazairi** [comment]
Emerged from a discussion during the fall 2019 working meeting: https://docs.google.com/document/d/1CnI-7xo5KFfd3btBH_hiGSrXnYVjNJHkB5DPoibXz08/edit

**Comment by glenrobson** [comment]
This has been covered in some detail here:

https://github.com/IIIF/cookbook-recipes/blob/master/recipe/index.md

Its also been in operation for over a year now.
