### ISSUE TITLE
Poster Image Displayed Before Interaction

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#13]
## Poster image displayed before interaction

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
I wish to provide the user with something to look at before they choose to start interacting with the object, and/or while they wait for it to load/buffer.

**Comment by tomcrane** [comment]
Discussed in WG meeting - this is the same modelling as for journals or newspapers, but it's worth producing a separate recipe for a journal splash / poster image. It will make it easier for people to find, and copy.

**Comment by triplingual** [comment]
Note to self: working example (more or less) of this idea in v2 at http://universalviewer.io/examples/?manifest=http://wellcomelibrary.org/iiif/b17307922/manifest#?c=&m=&s=&cv=&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb17307922%2Fmanifest and https://uv.netlify.app/#?c=&m=&s=&cv=&manifest=http%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb17307922%2Fmanifest (note the difference in placeholder image sizes)
