### ISSUE TITLE
Start

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#15]
## Start

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
I want the content to initialise somewhere other than its beginning.

**Comment by tomcrane** [comment]
Equivalent to 2.1 fixture

https://iiif.io/api/presentation/2.1/example/fixtures/65/manifest.json

**Comment by kirschbombe** [comment]
Per conversation in the cookbook meeting, adding a link to the `0015-start` branch with progress on this issue: https://github.com/IIIF/cookbook-recipes/tree/0015-start/recipe/0015-start

**Comment by glenrobson** [comment]
I've spoken to @tomcrane and this issue is available for someone to finish off. If your interested please assign the issue to yourself. This issue also relates to the following pull request:

https://github.com/IIIF/cookbook-recipes/pull/101

**Comment by kirschbombe** [comment]
I can finish this one :)

**Comment by kirschbombe** [comment]
https://preview.iiif.io/cookbook/0015-start/recipe/0015-start/
