### ISSUE TITLE
Using Transcripts with A/V Content

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#17]
## Using Transcripts with A/V Content

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
I have transcripts of sound recordings, of video recordings.

**Comment by aisaac** [comment]
Looking at https://preview.iiif.io/cookbook/0017-using-transcripts/recipe/0017-transcription-av/ I agree with the pattern used!

Again my only comment will be about the terminology. The sentence "While transcripts, captions, and subtitles each present some text interpretation of the A/V content, the ways they are consumed by the users differ." hints that each of these types of material is bound to be consumed in a specific way. But as the meta recipe rightly put, transcriptions alone may be provided and consumed in different ways. Maybe "the ways they can be consumed by the users differ" would be more appropriate wording?

In the same line, the title of the recipe could be refined, to indicate that the idea of this recipe is "providing access to transcription files", not "transcripts" in general (as readers could understand that transcripts could be also addressed by each of the other two 'transcript options' in the [meta-recipe](https://preview.iiif.io/cookbook/transcript-meta-recipe/recipe/0231-transcript-meta-recipe/)). NB: this would allow to perfectly align with the wording of the use case, which is beautifully clear!
