### ISSUE TITLE
Document that en-us in language maps will break the . notation 

### ISSUE THREAD

**Issue by azaroth42** [IIIF/cookbook-recipes#171]
Related to IIIF/api#1739, `@none` breaks the label.en pattern from working, but so does the use of hyphens in language names such as the very common `en-us` versus `en-gb`, or `en-latin` to add in script rather than locale.

We can't alias every possible hyphenated language, so just need to document that this scenario might occur.

(Unless someone has a brilliant idea?)

**Comment by kirschbombe** [comment]
This issue is fixed with recipe: #6
