### ISSUE TITLE
HTML in Annotations

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#19]
## Comments

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
Example of HTML in an annotation - needs a specific use case (annotation to link to / embed a cat gif/video?)

**Comment by tomcrane** [comment]
Equivalent to 2.1 fixtures

https://iiif.io/api/presentation/2.1/example/fixtures/51/manifest.json
https://iiif.io/api/presentation/2.1/example/fixtures/52/manifest.json
https://iiif.io/api/presentation/2.1/example/fixtures/54/manifest.json

**Comment by glenrobson** [comment]
First one handled by https://iiif.io/api/cookbook/recipe/0266-full-canvas-annotation/

Second one handled by: https://iiif.io/api/cookbook/recipe/0021-tagging/

HTML in an annotation could be covered by #105 but maybe a basic HTML annotation would be helpful.

**Comment by robcast** [comment]
Notes:
- Prezi3 talks about allowed HTML "in the `summary` property and the `value` property in the `metadata` and `requiredStatement`" https://iiif.io/api/presentation/3.0/#45-html-markup-in-property-values
- WebAnno uses HTML in example 5 of https://www.w3.org/TR/annotation-model/#embedded-textual-body and has no mention of allowed HTML
