### ISSUE TITLE
Implementing in localhost application

### ISSUE THREAD

**Issue by broy-github** [IIIF/cookbook-recipes#192]
Hello,

I want to implement it in my localhost application to show images in Universal Viewer.
How will be the manifest.json and config.json be called from my html please?
I want to link them as my local version from html.

I am using somehow like this:

`<div class="uv" data-locale="en-GB:English (GB),cy-GB:Cymraeg" data-config="http://localhost:60983/MyConfig.json" data-uri="http://localhost:60983/manifest.json" data-collectionindex="0" data-manifestindex="0" data-sequenceindex="0" data-canvasindex="0" data-xywh="-2880,-100,8039,2947" data-rotation="0" style="width:800px; height:600px; background-color: #000"></div>
        <script type="text/javascript" id="embedUV" src="~/uv-2.0.0/lib/embed.js"></script>
        <script type="text/javascript">/* wordpress fix */</script>`

But, I am getting error as follows:
bundle.min.js:9 **Uncaught (in promise) TypeError: Cannot read property 'getIIIFResourceType' of null**
    at Bootstrapper._loaded (bundle.min.js:9)
    at bundle.min.js:9

Please help me.

Thanks.

**Comment by glenrobson** [comment]
Hi,

I'm afraid I don't think your question fits into the Recipe repository. Your probably best off asking on the UniversalViewer Slack channel which you can join here:

https://docs.google.com/forms/d/e/1FAIpQLSeHLD0kng5aXvGFsNN_tJGsZMTnp08Hv2F6kdGsJRb6bT0NWw/viewform

Hope that helps.

Glen
