### ISSUE TITLE
Place Manifest to an Area on a Web Map

### ISSUE THREAD

**Issue by thehabes** [IIIF/cookbook-recipes#195]
## Recipe Name  
Geolocate a Manifest to a Polygon
- [Index](https://github.com/IIIF/cookbook-recipes/blob/0195-geolocate-manifest-to-polygon/recipe/0195-geolocate-manifest-to-polygon/index.md)
- [Preview](https://preview.iiif.io/cookbook/0195-geolocate-manifest-to-polygon/recipe/0195-geolocate-manifest-to-polygon/)

## Use case  
There is a photo taken from an event being encoded as a IIIF Presentation API 3.0 Manifest. I would like to geolocate the Manifest to the city in which the event took place, since I do not know the exact coordinates of the photo.

## Demo UI
http://geo.rerum.io/geolocate/viewAnnotations.html?manifest=https://preview.iiif.io/cookbook/0195-geolocate-manifest-to-polygon/recipe/0195-geolocate-manifest-to-polygon/manifest.json

**Comment by glenrobson** [comment]
Bryan to create a pull request.

**Comment by glenrobson** [comment]
This has been done.
