### ISSUE TITLE
Simplest Manifest - Single Audio File

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#2]
## Simplest Manifest - Single Audio File

https://github.com/IIIF/cookbook-recipes/blob/master/recipe/0002-mvm-audio/index.md

## Use case  
You have a single audio resource available on the web and want to present it in a IIIF environment.

**Comment by mikeapp** [comment]
https://preview.iiif.io/cookbook/themed/recipe/0002-mvm-audio/

**Comment by tomcrane** [comment]
Title has changed so recipe needs updating

**Comment by triplingual** [comment]
Recipe complete at https://iiif.io/api/cookbook/recipe/0002-mvm-audio/
