### ISSUE TITLE
Add identifying graphic with `logo`

### ISSUE THREAD

**Issue by triplingual** [IIIF/cookbook-recipes#217]
## Add identifying graphic with `logo`

[https://iiif.io/api/presentation/3.0/#logo](https://iiif.io/api/presentation/3.0/#logo)

## Use case  
So a viewer can display an unmistakable indication that displayed resources are from our repository, as an organization we would like to provide information about our official logo to a viewer.

**Comment by glenrobson** [comment]
This seems to be covered by the provider recipe.

https://github.com/IIIF/cookbook-recipes/issues/234
