### ISSUE TITLE
Add is "This page was helpful…"

### ISSUE THREAD

**Issue by glenrobson** [IIIF/cookbook-recipes#226]
User Feedback for recipes like:

https://support.google.com/photos/answer/6128850?hl=en&ref_topic=6128857  
https://support.microsoft.com/en-us/office/add-an-email-account-to-outlook-6e27792a-9267-4aa4-8bb6-c84ef146101b

Suggested by @cubap

**Comment by triplingual** [comment]
For what it's worth, I like the UX much better in the Google version. I had to search for the MSFT one.

**Comment by cubap** [comment]
I've started work on this. I imagine the process will be a bit different from a recipe, but I've started a fork just the same https://github.com/iiif-feedback/cookbook-recipes and will update this ticket when there is feedback or updates.

At the moment, I cannot install Ruby on my work machine by myself, so we're waiting for support, but I can run most of these pages in my head and get a good start at least. I intend to create a small module like `links.md` that can be included, though this only targets the recipe pages.

There are more complicated approaches, but I think showing that the simplest works first is a good start. I will have a 👍/👎 form with a text box that can be included and sent up (matching roughly the [GitHub docs](https://docs.github.com/en/rest/guides) format).

![image](https://user-images.githubusercontent.com/1119165/105393824-70e93400-5be2-11eb-91d2-f0aa0749e05b.png)

This template would wrap the recipes and store the responses on a Google Sheet, but can be reassigned to whatever works for IIIF.

**Comment by glenrobson** [comment]
This is sounding great. I think rather than the `links.md` it might be better to follow how we include the manifest stuff in:

https://github.com/IIIF/cookbook-recipes/blob/master/_includes/manifest_links.html

and its embedded in a recipe like so:

```
{% include manifest_links.html viewers="UV, Mirador" manifest="manifest.json" %}
```

in fact I should probably move the acroyms.md and links.md into the layout here:

https://github.com/IIIF/cookbook-recipes/blob/master/_layouts/recipe.html

then I could add this feedback import to that so that its automatically included on all recipes. 

Storing it in Google Sheets sounds great. Will there be any issues with API keys being accessible? 

Regarding working on a fork it may be best to work on the IIIF version and create a branch. This will mean you get the preview functionality for free. I don't think this needs to go to the TRC for approval like recipes do.

**Comment by cubap** [comment]
Sounds good. I cannot make branches without making a fork, so can you add `cubap` as a contributor, please?

The plan makes sense to me and I will follow it. I believe I have a solution for the API keys, but I'll need to try it out. If it works with the dummy account I set up, we can move ownership of the records.

**Comment by glenrobson** [comment]
Sorry I should have thought. I've added you to the iiif-recipes team so you should now be able to create branches. 

Looking forward to hearing the possible key solution once you've tested it.
