### ISSUE TITLE
Chronology with navDate

### ISSUE THREAD

**Issue by triplingual** [IIIF/cookbook-recipes#230]
## Chronology with `navDate`

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
The recipe user has one or more periodical articles (journal, magazine, etc.) in IIIF form and would like to communicate their dates to a consuming client for the client to put in a chronological order.

**Comment by glenrobson** [comment]
Just for completeness here is the notes from the last cookbook call:

 * Simple manifests better
 * Probably need to have multiple Canvases
 * UV will allow browsing by date, but only on a Collection of Manifests
 * Unclear which viewers support and in which way
 * Can link to newspapers recipe in Related for an example of a run of titles
 * Could use something from https://www.loc.gov/maps/?q=Chesapeake+and+Ohio+Canal&fa=contributor%3Aunited+states.+national+park+service&st=list&c=100
    * But use one and mention in Example section that there are others
    * Item fixtures link https://fixtures.iiif.io/info.html?file=/images/loc/chesapeake_map/88695674.jpg
