### ISSUE TITLE
Transcripts, Captions, and Subtitles - General Considerations

### ISSUE THREAD

**Issue by mcwhitaker** [IIIF/cookbook-recipes#247]
## Recipe Name  
Meta Recipe for Captions, Subtitles, and Transcripts

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
In the May/2021 TRC meeting it was proposed that, before working on the individual recipes for Captions, Subtitles, and Transcripts, a Meta Recipe would be helpful with the discussion about the various cases and how they differ.

**Comment by aisaac** [comment]
This recipe mentions other recipes including some to be written in the farther future. But shouldn't 074 (Video with captions in multiple languages) mentioned too?

**Comment by aisaac** [comment]
I have read the draft (sorry this is so late) and I think I like the direction it sets for the other recipes (NB: this is before I've read these other recipes!).

I must say that while reading this I had a 100$ ontological question ;-)... Considering that  Captions and Subtitles are a case of 2b, then the reader may wonder whether captions and subtitles are a kind of transcript! Should the recipe clarify this?
