### ISSUE TITLE
0013-placeholderCanvas seems not a valid IIIF manifest, missing label

### ISSUE THREAD

**Issue by giacomomarchioro** [IIIF/cookbook-recipes#251]
Hi all, 
just wondering if [0013-placeholderCanvas](https://github.com/IIIF/cookbook-recipes/tree/master/recipe/0013-placeholderCanvas)  is compliant with 3.0?

The manifest doesn't have any label while [it should](https://iiif.io/api/presentation/3.0/#label).

https://github.com/IIIF/cookbook-recipes/blob/993b3bb47aa019a81bd36e2c036ef16013f79701/recipe/0013-placeholderCanvas/manifest.json#L3-L6

**Comment by triplingual** [comment]
Good catch! I'll address this in the `placeholderCanvas` recipe.

**Comment by triplingual** [comment]
Fixed in PR https://github.com/IIIF/cookbook-recipes/pull/264
