### ISSUE TITLE
Tagging Annotation with External Resource

### ISSUE THREAD

**Issue by triplingual** [IIIF/cookbook-recipes#258]
## Recipe Name  
Tagging Annotation with External Resource

## Use case  
Where #21 gave the simplest tagging annotation, using a Textual Resource to label a feature in the image, this recipe would start to move into the preferable scenario, a tag that connects to an external web resource, Wikidata perhaps.

**Comment by glenrobson** [comment]
Notes from the Cookbook editor call
 * See [Slack conversation](https://iiif.slack.com/archives/CPLTX1ZD0/p1630334013000900) between Rob and Niqui O’Neill
 * Solution for referenced vocabulary
 * Need conversations about use cases: 
    * What are purposes of people who are implementing linked data into their annotations?
    * This might lead to identifying a need for a new kind of body, e.g., a SpecificResource with a Label
    * Would also guide what gets written in the “Use Case” section of the recipe
    * Ask Niqui directly

Consider using Europeana pattern:
```
{
  "motivation": "oa:tagging",
  "body": [
    {
      "@type": "SpecificResource",
      "source": "http://sws.geonames.org/2988507"
    },
    {
      "@type": "TextualBody",
      "value": "Paris",
      "language": "en"
    }
  ],
  "target": "http://data.europeana.eu/item/09102/_UEDIN_214"
}
```
 * Include both SpecificResource and TextualBody, make sure recipe body has caveat about viewers not inferring any connection between multiple body parts
