### ISSUE TITLE
Table of contents (ranges) - acts of an opera

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#26]
## Table of contents (ranges) - acts of an opera
(this will usually be the same as the issue name)

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
The logical structure of an audio recording - an opera, with a hierarchy of acts, arias, etc.

**Comment by glenrobson** [comment]
Has this been done now?

**Comment by glenrobson** [comment]
Group decided on 28th Jan to close due to it being related to #64 and #65 which have been written.
