### ISSUE TITLE
Incorrect link target in "Provider"

### ISSUE THREAD

**Issue by triplingual** [IIIF/cookbook-recipes#263]
Moving comment from @regisrob on the PR for #234 (https://github.com/IIIF/cookbook-recipes/pull/235#issuecomment-891085954) here as an Issue to be resolved.

> Late feedback on recipe #234 (https://iiif.io/api/cookbook/recipe/0234-provider/): in the "Related Recipes" section, the link to "Linking to Structured Metadata" recipe is wrong (currently points to the navDate recipe)

**Comment by glenrobson** [comment]
Done
