### ISSUE TITLE
0068-newspaper: ALTO Resource doesn't have CORS headers set

### ISSUE THREAD

**Issue by jbaiter** [IIIF/cookbook-recipes#277]
Currently the ALTO at https://iiif.io/api/cookbook/recipe/0068-newspaper/newspaper_issue_1-alto_p1.xml does not have the `Access-Control-Allow-Origin: *` set, which makes processing the ALTO from client-side code impossible from outside of the `iiif.io` Domain.
This impacts the [Mirador 3 Text Overlay Plugin](https://github.com/dbmdz/mirador-textoverlay), where I wanted to use the manifest from the recipe as an example.

**Comment by glenrobson** [comment]
Thanks @jbaiter it should have CORS set but it looks like currently it only sends them for JSON files. Ill look into it now.

**Comment by glenrobson** [comment]
Should be fixed when this deploys in 10mins or so:

https://github.com/IIIF/iiif-reverse-proxy-app/pull/22
