### ISSUE TITLE
Dealing with Missing images

### ISSUE THREAD

**Issue by glenrobson** [IIIF/cookbook-recipes#283]
## Recipe Name  
Missing images in sequence. 

## Use case  
I have  a manuscript which has an image missing. I want to included a canvas with some content to show the user that there should/could be an image there and also make sure the recto/verso paged functionality isn't thrown due to this missing image. 

See this example: https://github.com/IIIF/api/issues/33

**Comment by regisrob** [comment]
Live examples in Mirador 2 (manuscripts with missing pages represented as empty canvases):
https://demos.biblissima.fr/florus/florus-dispersus/mirador/
https://demos.biblissima.fr/bbmn-1713/mirador/

**Comment by kirschbombe** [comment]
Thanks for the example links, @regisrob! I used the Biblissima examples last year to model how we approach this here at UCLA :)

**Comment by glenrobson** [comment]
We also tried this at the NLW: https://glenrobson.github.io/iiif/2021/06/04/NLW-Journals.html

**Comment by glenrobson** [comment]
Just looking at @regisrob example it looks like they also have empty canvases (from https://demos.biblissima.fr/iiif/metadata/florus-dispersus/manifest.json):

```
{

    "@id": ["http://demos.biblissima-condorcet.fr/iiif/metadata/florus-dispersus/canvas/canvas-1"](http://demos.biblissima-condorcet.fr/iiif/metadata/florus-dispersus/canvas/canvas-1),
    "@type": "sc:Canvas",
    "label": "Lacune (32r)",
    "width": 860,
    "height": 1200

},
```

@regisrob how do you get the custom thumbnail to appear? Is that a local customisation of Mirador? 

Also this example:
```
{

    "@id": ["https://iiif.biblissima.fr/bbmn-1713-t1/canvas/c-1"](https://iiif.biblissima.fr/bbmn-1713-t1/canvas/c-1),
    "@type": "sc:Canvas",
    "label": "p.1",
    "width": 3464,
    "height": 4898,
    "metadata": [
        {
            "label": "Cote",
            "value": "Page non retrouvée"
        },
        {
            "label": "Titre",
            "value": "Catalogus quorumdam Manuscriptorum Bibliothecae Vaticanae"
        },
        {
            "label": "Notice",
            "value": ["https://www.unicaen.fr/puc/sources/thecae/maur/BBMN_Roma_Bibl.Vaticana_1738_01"](https://www.unicaen.fr/puc/sources/thecae/maur/BBMN_Roma_Bibl.Vaticana_1738_01)
        }
    ]

},
```
from https://iiif.biblissima.fr/bbmn-1713-t1/manifest.json

**Comment by glenrobson** [comment]
Related discussion on api issue: https://github.com/IIIF/api/issues/1017

**Comment by glenrobson** [comment]
Also this discussion in mirador: https://github.com/ProjectMirador/mirador/pull/1231

**Comment by kirschbombe** [comment]
@glenrobson - if you load those manifests in UV or the Mirador demo, they lose the placeholder thumbnails. It would be great if the community could agree on a way that viewers could handle empty canvases that could be implemented in each of the viewers. Short of that, it seems like local customizations (like Biblissima) or using a placeholder image on a Canvas where the image is missing are the current solutions.

**Comment by kirschbombe** [comment]
> Also this discussion in mirador: [ProjectMirador/mirador#1231](https://github.com/ProjectMirador/mirador/pull/1231)

It looks like Mirador 2 addressed empty canvases, but it doesn't look like that made it into M3?

**Comment by glenrobson** [comment]
It looks like it was never merged in mirador 2 but it looks very similar to @regisrob implementation.

**Comment by regisrob** [comment]
@glenrobson Yes it was a local customization in Mirador 2, but I cannot remember why it was never merged in the codebase, nor why the placeholder text and thumbnail for empty canvases has not been implemented in Mirador 3...
I am not completely sure but I remember [this first demo](https://demos.biblissima.fr/florus/florus-dispersus/mirador/) was entirely custom (kind of a hack) to make M2 support empty canvases. The [second one](https://demos.biblissima.fr/bbmn-1713/mirador/) may be based on Johannes's work mentioned above, but I am not completely sure.
