### ISSUE TITLE
Viewer Matrix - making the order of the viewers consistent

### ISSUE THREAD

**Issue by julsraemy** [IIIF/cookbook-recipes#287]
On the [Viewer Matrix](https://iiif.io/api/cookbook/recipe/matrix/), Mirador is mentioned first and UV second most of the time (except the last paragraph in `Which viewers are included?`). 

But on each recipe, the `View In Universal Viewer` appears first and then `View in Mirador`. 

I would suggest to keep the above order and rearrange the Matrix.

**Comment by glenrobson** [comment]
Should be fixed once its finished the deployment process.
