### ISSUE TITLE
Addressing a Region

### ISSUE THREAD

**Issue by triplingual** [IIIF/cookbook-recipes#299]
**Recipe description mooted but left for comment thread context purposes. New description [in comment below](https://github.com/IIIF/cookbook-recipes/issues/299#issuecomment-1077630335)**

## Recipe Name  
Image Rotation of a Region

## Use case  
You have a region of an image that you want to rotate by default in presenting it to viewers. For one example, your images are of codex spreads, and one side of the view has text content oriented perpendicularly to the other half.

Comments and/or refinements welcome.

**Comment by glenrobson** [comment]
I think it could also just be that you want a region of a iiif image which isn't rotated. For example I want to create a manifest of Newspaper articles which are regions of various Newspaper pages.

**Comment by triplingual** [comment]
Do you mean that this issue is not about rotation or are you saying that the use case includes both 1) regions that are undesirably rotated and ~should be rotated and 2) regions that are not undesirably rotated but that you want to rotate?

**Comment by glenrobson** [comment]
I wonder if we should re-focus this recipe to be about regions without rotation as we are already doing rotation of a full canvas in #40. The focus and use case for this recipe could be on a region with a small mention in the implementation notes of rotation and linking to #40. 

What do you think?

**Comment by glenrobson** [comment]
Discussion on call. Merge with css rotation ticket so we can compare and contrast

**Comment by triplingual** [comment]
Further discussion elucidated that this recipe will become only for discussion addressing a region, without rotation. #39 and #40 will merge into #40 to discuss rotation as a use case and include both the image service approach and the CSS approach.

Title of this one to change accordingly.

**Comment by triplingual** [comment]
**NEW DESCRIPTION**

## Recipe Name  
Addressing a Region

## Use case  
You have a region of an image that you want to present independently.

Comments and/or refinements welcome.
