### ISSUE TITLE
Simplest Manifest - Single Video File

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#3]
## Simplest Manifest - Single Video File

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
You have a video resource available on the web and want to present it in a IIIF environment.

**Comment by mikeapp** [comment]
https://preview.iiif.io/cookbook/themed/recipe/0003-mvm-video/

**Comment by tomcrane** [comment]
Title updated, so recipe needs updating.

**Comment by triplingual** [comment]
Recipe complete at https://iiif.io/api/cookbook/recipe/0003-mvm-video/
