### ISSUE TITLE
Bound multi-volume work

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#31]
## Bound multi-volume work

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
Are we talking Sammelband (for which there is a later issue) or are we talking a single-volume _Lord of the Rings_?

**Comment by kirschbombe** [comment]
I'm thinking a good example might be music scores that are often bound together, although I wouldn't call it a "multi-volume work", maybe something like "multiple works bound together"? "multiple works in a single binding"? The example would use a single manifest with ranges (as opposed to multiple manifests brought together with a collection)
