### ISSUE TITLE
Simple Collections

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#32]
## Paged Collections

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
See https://github.com/IIIF/api/issues/1343

**Comment by glenrobson** [comment]
Note we mention collections here: https://iiif.io/api/cookbook/recipe/0030-multi-volume/

but probably still useful to have a basic collection recipe.

**Comment by glenrobson** [comment]
As discussed a simple collection with 2/3 manifests in it.

**Comment by saracarl** [comment]
Just an encouraging note to finish this one, since I was looking for a test collection manifest today and was surprised not to see one!

**Comment by mathewjordan** [comment]
@saracarl Thank you for the push. I do have the [PR](https://github.com/IIIF/cookbook-recipes/pull/371) that that  became stale. I'll work to complete it post-conference.

**Comment by mialondon** [comment]
A bump following the IIIF workshop at EuropeanaTech this week - it'd be great to develop thinking about collections!

**Comment by glenrobson** [comment]
Completed in: https://github.com/IIIF/cookbook-recipes/pull/371
