### ISSUE TITLE
Locational Information for each Manifest in a Collection

### ISSUE THREAD

**Issue by thehabes** [IIIF/cookbook-recipes#324]
## Recipe Name  
Locational Information for each Manifest in a Collection

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
I have a Collection of Manifests filled with media.  Most or all of that media has coordinate information, like where the photograph was taken or where the object in the photograph resides, and more.  I would like the coordinate information to be collected with my IIIF resource types and to be displayed on a web map.

**Comment by glenrobson** [comment]
This will be covered in #318 and also with the simple collection #32
