### ISSUE TITLE
I want to annotate a particular layer of an image

### ISSUE THREAD

**Issue by glenrobson** [IIIF/cookbook-recipes#326]
## Recipe Name  
Annotating Image Layer

## Use case  
I have found a watermark on one of the multi spectral images and I want to annotate it. It doesn't appear on all layers to I don't want to annotate the canvas.

Questions:
 * Where do you put this annotation? In `annotations` in the image?

**Comment by giacomomarchioro** [comment]
We decided to focus the efforts on the `choice` elements.
Content resources may have annotations hence an annotation was created for the X-Ray image of the [choice example](https://iiif.io/api/cookbook/recipe/0033-choice/) targeting the ID of the X-Ray image and adding a fragment selector:
```
                    "annotations": [
                      {
                        "id": "https://preview.iiif.io/cookbook/333X-choice-annotation/recipe/333X-choice-annotation/page/p2/1",
                        "type": "AnnotationPage",
                        "items": [
                          {
                            "id": "https://preview.iiif.io/cookbook/333X-choice-annotation/recipe/333X-choice-annotation/annotation/p0002-tag",
                            "type": "Annotation",
                            "motivation": "tagging",
                            "body": {
                              "type": "TextualBody",
                              "value": "A group of skulls.",
                              "language": "en",
                              "format": "text/plain"
                            },
                            "target": "https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-xray/full/max/0/default.jpg#xywh=810,900,260,370"
                          }
                        ]
                      }
                    ],
```
The resulting manifest can be accessed here: https://api.npoint.io/79fc487ebc405f7b0cec or cloned at [this link](https://www.npoint.io/docs/79fc487ebc405f7b0cec).

**Compatibility with the viewers**
Mirador does not support the viewing of the annotation, at the moment is possible only to annotate both layers targeting the canvas like in this manifest https://www.npoint.io/21d8303a2fecf721dd2a editing mode [ at this link](https://www.npoint.io/docs/21d8303a2fecf721dd2a).

**Comment by mikeapp** [comment]
One question I had is whether the annotation itself should contain a reference to the Canvas context if that is relevant to the annotation.   Web Annotation's `scope` might be one way to do this:  https://www.w3.org/TR/annotation-model/#scope-of-a-resource

**Comment by giacomomarchioro** [comment]
> One question I had is whether the annotation itself should contain a reference to the Canvas context if that is relevant to the annotation. Web Annotation's `scope` might be one way to do this: https://www.w3.org/TR/annotation-model/#scope-of-a-resource

It seems a very good idea, I'll edit the recipe to include it.
