### ISSUE TITLE
Simple Manifest - Audio Example section is inaccurate

### ISSUE THREAD

**Issue by markpbaggett** [IIIF/cookbook-recipes#327]
The "Example" section of [0002 Simple Manifest - Audio](https://iiif.io/api/cookbook/recipe/0002-mvm-audio/) is not accurate.  The section reads:

> This example shows a Manifest with a single Canvas that lasts for 3600 seconds, or exactly one hour. It has a single audio file (audio-sample.mp4) which is associated with it. The mp4 also has a duration of exactly one hour.

but the fixture has a duration of `1985.024` and the mp4 is named `128Kbps.mp4`.

A more accurate example would be something like:

>  This example shows a Manifest with a single Canvas that lasts 1985.024 seconds. It has a single audio file (128Kbps.mp4) which is associated with it. The mp4 also has a duration of 1985.024 seconds.

**Comment by triplingual** [comment]
Fixed by abc0c11f
