### ISSUE TITLE
0017-transcription-av: problems with viewers

### ISSUE THREAD

**Issue by nvanderperren** [IIIF/cookbook-recipes#329]
In the Examples section, the text says:

> In Mirador, a given transcript is made available within the sidebar menu, which can be toggled open by using the ‘Sidebar toggle’ (hamburger) button on the top left corner of the viewer.

But in [Mirador](https://projectmirador.org/embed/?iiif-content=https://iiif.io/api/cookbook/recipe/0017-transcription-av/manifest.json), I can't find the transcript.

Then UV:

> In Universal Viewer, to access the transcript use the ‘Download’ link on the bottom left corner of the viewer.

When I open [UV](https://uv-v3.netlify.app/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fiiif.io%2Fapi%2Fcookbook%2Frecipe%2F0017-transcription-av%2Fmanifest.json), I get the error "No renderer found. Download File: https://fixtures.iiif.io/video/indiana/volleyball/volleyball.txt". It's also impossible to play the video.

**Comment by glenrobson** [comment]
Looks like it could be a CORS issue on at least the video file.

**Comment by glenrobson** [comment]
I haven't changed anything but both the text file and the video have the following CORS headers set:

```
access-control-allow-origin: *
```

I tried removing the transcript to see if it was a problem with the video but the UV plays the video if the transcript is removed. So I think the correction suggested at the start is correct.
