### ISSUE TITLE
Choice - multispectral flavoured example, with image services

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#34]
## Choice - multispectral flavoured example, with image services
PR: https://github.com/IIIF/cookbook-recipes/pull/115
Preview: https://preview.iiif.io/cookbook/3333-choice/recipe/0034-choice-with-image-services/

## Use case  
I have a stack of multispectral, aligned images of a painting.

**Comment by tomcrane** [comment]
Equivalent to 2.1 fixture

https://iiif.io/api/presentation/2.1/example/fixtures/29/manifest.json

**Comment by tomcrane** [comment]
This recipe should be a variation on #33 - it exists to provide an alternative fixture, with image services (#33 is static images). It should not repeat the use case discussion, but refer to it.

**Comment by kirschbombe** [comment]
Closing this as duplicate - this use case is covered with #33 and PR #115
