### ISSUE TITLE
Support multiple languages in an Annotation body 

### ISSUE THREAD

**Issue by glenrobson** [IIIF/cookbook-recipes#346]
## Recipe Name  
Annotation Language 

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
Came up in the HTML annotation recipe it would be useful to be able to show how you need two bodies one for each language.

**Comment by triplingual** [comment]
+ Consider something from NICH in Japan, would need to message them to say what we are planning to use
+ Canvas-level annotation

**Comment by triplingual** [comment]
Looks like the data model uses language as the example for their discussion of body choice: https://www.w3.org/TR/annotation-model/#choice-between-bodies
