### ISSUE TITLE
Foldouts, etc ( non-paged interlude (flaps vs maps) Foldouts, Flaps and Maps)?

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#35]
## Foldouts, etc (Choice or non-paged interlude (flaps vs maps))?

PR: https://github.com/IIIF/cookbook-recipes/pull/115
Preview: https://preview.iiif.io/cookbook/3333-choice/recipe/0035-foldouts/

## Use case  
My book has some fold-out maps

**Comment by tomcrane** [comment]
The intention with this issue is to draw out the distinction with Choice #33, #34 

An image of a book page with a flap open or closed can be one Canvas with a `Choice` of views, whereas a foldout map is not the same Canvas as the folded version, it's another Canvas in the sequence, but marked `non-paged` to preserve the paged sequence.

**Comment by glenrobson** [comment]
Looking through the recipe this looks more like its focusing on non-paged rather than choice so we are going to remove choice from the title.

**Comment by glenrobson** [comment]
Focus use case on handling a canvas which is in the sequence but would break the 2-up view.
