### ISSUE TITLE
Multiple images (master/detail)

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#36]
## Multiple images (master/detail)

PR: https://github.com/IIIF/cookbook-recipes/pull/115
Preview: https://preview.iiif.io/cookbook/3333-choice/recipe/0036-composition-from-multiple-images/

## Use case  
A page of a manuscript from which an illumination has been cut out.

**Comment by tomcrane** [comment]
Equivalent to 2.1 fixtures

https://iiif.io/api/presentation/2.1/example/fixtures/30/manifest.json
https://iiif.io/api/presentation/2.1/example/fixtures/31/manifest.json

**Comment by tomcrane** [comment]
This recipe needs to bring out the distinction with Choice (#33, #34), Foldouts (#35), and multiple images that are all part of a scene.

Whereas the flap open/flap closed images of #33 are a `Choice`, the multiple media of Fire (https://tomcrane.github.io/fire/) are clearly not - the scene is composed, deliberately in a certain order and certain time.

Clients could still offer the user control over the visibility of elements, but the simplest and default case would be not to do this - it would be to render the scene as is.

For spatial content this means rendering the scene as described.
For this the Châteauroux example is useful:

![](https://iiif.irht.cnrs.fr/iiif/Ch%C3%A2teauroux/B360446201_MS0005/jp2/B360446201_MS0005_0038/full/400,/0/default.jpg)  ![](https://gallica.bnf.fr/iiif/ark:/12148/btv1b10511139b/f1/full/200,/0/default.jpg)

In its source manifest this is not a `Choice`:

https://iiif.biblissima.fr/chateauroux/B360446201_MS0005/manifest.json
(search for "0038" for the first Canvas with an illumination)

While the specialist Châteauroux demo (https://demos.biblissima.fr/chateauroux/osd-demo/) gives users the ability to see the illuminations, by default a general client should render both images from the off.

There is no difference between this and _Fire_ in that respect.

**Comment by jrgriffiniii** [comment]
This recipe has been moved to https://github.com/IIIF/cookbook-recipes/blob/master/recipe/0036-detail-image/index.md

**Comment by tomcrane** [comment]
I suggest a change to the title of this recipe:

_Composition of one view from multiple image sources_

...which is a bit clearer I think.
