### ISSUE TITLE
Remove UV support from Start recipe (#15) when Clover is available

### ISSUE THREAD

**Issue by triplingual** [IIIF/cookbook-recipes#360]
When we wrote the recipe, UV was the only viewer we had that supported A/V playback, so we wanted to show at least that aspect. When Clover passes as an endorsed viewer, we'll have two A/V viewers. Since there's little point to having two viewers listed in the recipe as _partial_ (when the only partialness is playing video at all), it seems better to have none. Yes?

**Comment by glenrobson** [comment]
I agree it no longer seems appropriate to give this a partial. For info here is the recipe link with note on UV support:

https://iiif.io/api/cookbook/recipe/0015-start/
