### ISSUE TITLE
Mirador should only be partial on HTML in Annotations

### ISSUE THREAD

**Issue by dnoneill** [IIIF/cookbook-recipes#363]
## Recipe Name  
HTML in Annotations

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)
https://github.com/IIIF/cookbook-recipes/blob/master/recipe/0019-html-in-annotations/index.md
## Use case  
I tried creating an annotation with a <strong> tag. The text displays, the HTML does not. It looks like Mirador only supports partial HTML annotations.

**Comment by triplingual** [comment]
Do you have a link to the annotation you created or a whole manifest with it?

**Comment by glenrobson** [comment]
and do you mean a tagging annotation or a specific HTML tag that doesn't work?

**Comment by dnoneill** [comment]
@triplingual https://projectmirador.org/embed/?iiif-content=https://dnoneill.github.io/testworkspace/manifests/pe/000012/manifest.json

@glenrobson <strong> doesn't work in Mirador3, though I would assume there are probably other HTML tags that don't work if a tag that basic doesn't work but I haven't done any kind of survey of tags.

**Comment by triplingual** [comment]
As I'm reading the spec and recipe (which links to the spec discussion of acceptable elements), `<strong>` is not expected to be supported. 

Recipe:
> These are the tags that the client may support and others may be stripped: a, b, br, i, img, p, small, span, sub, and sup tags and href attributes on the a tag, and src and alt on the img tag.

[Spec](https://iiif.io/api/presentation/3.0/#45-html-markup-in-property-values):
> The content must be well-formed XML and therefore must be wrapped in an element such as p or span. *It doesn't look like yours has this structure, but I don't think that's the issue.*

> Clients should allow only a, b, br, i, img, p, small, span, sub and sup tags. Clients may choose to remove any and all tags, therefore it should not be assumed that the formatting will always be rendered.

It's a tricky thing, the more I think about it, to talk about "support" when a client has the right to remove any or all elements. There's no visible difference between "supports but removes all elements" and "does not support". Implicitly, I guess, when we say "supports" for this recipe, we mean "renders some or all of the permissible HTML elements".

**Comment by dnoneill** [comment]
@triplingual Gotcha. My bad. I did not understand that in the spec. I will close the issue.

**Comment by DiegoPino** [comment]
Hi. This is not a fixed rule in Mirador (can be configured).  See https://github.com/ProjectMirador/mirador/blob/22c2ca645d4f46ccc4a08c5e32a42f9e00ad3cbf/src/config/settings.js#L239

For all HTML sanitization rules https://github.com/ProjectMirador/mirador/blob/22c2ca645d4f46ccc4a08c5e32a42f9e00ad3cbf/src/lib/htmlRules.js

**Comment by dnoneill** [comment]
@DiegoPino Thanks so much. Solves one of my problems :)
