### ISSUE TITLE
Merge artifact adding ugly content

### ISSUE THREAD

**Issue by triplingual** [IIIF/cookbook-recipes#378]
In `_includes\links.md` there's [a stray line](https://github.com/IIIF/cookbook-recipes/blob/c352189a97cbd9d313a7af7d81a45c77fb80b303/_includes/links.md?plain=1#L23), seemingly from an incomplete merge 
cleanup, that's adding garbage to the bottom of any file that includes `links.md`.

**Comment by digitaldogsbody** [comment]
Cause of #369
