### ISSUE TITLE
Old recipe's limitations about viewers

### ISSUE THREAD

**Issue by triplingual** [IIIF/cookbook-recipes#381]
in #117, Mirador was the only viewer to support the use case when the recipe was written, and text was included that articulated that situation. This should get edited to reflect the addition of Clover as a supporting viewer.
Offending text:
> In Mirador, the sole viewer that uses it as of this writing, the Manifest thumbnail only displays when the site visitor uses “Add a resource” to change the loaded or active Manifests.

**Comment by triplingual** [comment]
Direct link to recipe: https://iiif.io/api/cookbook/recipe/0117-add-image-thumbnail/

**Comment by glenrobson** [comment]
Cookbook authors think this is a good change.
