### ISSUE TITLE
Add reference to registry in the seeAlso recipe

### ISSUE THREAD

**Issue by glenrobson** [IIIF/cookbook-recipes#384]
Now we have some [metadata formats](https://github.com/IIIF/trc/milestone/38) in the registry we should encourage people to use them in the seeAlso.

**Comment by glenrobson** [comment]
Cookbook group seems a good change.

**Comment by triplingual** [comment]
Pending population of registry

**Comment by glenrobson** [comment]
Recipe: https://iiif.io/api/cookbook/recipe/0053-seeAlso/

**Comment by glenrobson** [comment]
Profiles: https://iiif.io/api/registry/profiles/

**Comment by triplingual** [comment]
Recipe needs text explaining that manifest creators/editors should look in the registry for the URI to use as the value to the profile property under `seeAlso`, and include a link to the registry (above from @glenrobson)

**Comment by regisrob** [comment]
Hi @glenrobson @triplingual, I should have put my comment on this issue rather than on the PR: https://github.com/IIIF/cookbook-recipes/pull/457#issuecomment-1973378906. Am I misunderstanding something about the reference to the `id` field in this recipe?

**Comment by glenrobson** [comment]
Sorry Regis I missed the comment. Ill re-open this so we can discuss on Friday and get back to you.

**Comment by glenrobson** [comment]
Cookbook agreed that it should mention `profile` not `id` in the recipe:

https://iiif.io/api/cookbook/recipe/0053-seeAlso/

in the implementation notes and example.

**Comment by glenrobson** [comment]
This is now fixed. See above merge.
