### ISSUE TITLE
Image with CSS Rotation

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#39]
## Image with CSS Rotation

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
I want to include an image on the canvas, but it's upside down (or needs other rotation)

**Comment by tomcrane** [comment]
Equivalent to 2.1 fixture

https://iiif.io/api/presentation/2.1/example/fixtures/39/manifest.json

**Comment by glenrobson** [comment]
Reference in iiif 2.1: https://iiif.io/api/presentation/2.1/#rotation

2 options one using css or second using image selector: https://iiif.io/api/annex/openannotation/

**Comment by glenrobson** [comment]
Use this one if you want to rotate the image but the image service doesn't support rotation.

**Comment by triplingual** [comment]
To be merged with #40 into a single cookbook recipe with 2 manifests
