### ISSUE TITLE
Image different size to canvas

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#4]
## Image different size to canvas  

https://github.com/IIIF/cookbook-recipes/blob/master/cookbook/0004-canvas-size/index.md

## Use case  
(e.g.,) You have a very small image that you hope to later replace by a higher resolution image.  
Pedagogy: demonstrate the difference between canvas coordinate space and content dimensions.

**Comment by tomcrane** [comment]
Equivalent to 2.1 fixture: https://iiif.io/api/presentation/2.1/example/fixtures/26/manifest.json
(at https://github.com/IIIF/api/blob/master/source/api/presentation/2.1/example/fixtures/26/manifest.json)

**Comment by azaroth42** [comment]
Intent: Stretch or squash to fit the image into the canvas space.

**Comment by rsinghal** [comment]
https://github.com/IIIF/cookbook-recipes/blob/master/recipe/0004-canvas-size/index.md

**Comment by sredick** [comment]
several items that used to have masters but then they were lost; now they only have jpgs. they ingest the jpgs, then tell the studio to take more masters, but in the meantime they live with jpgs

**Comment by saracarl** [comment]
We have several items that used to have masters, but not we only have JPEGs.  We have an annotation project, we ingest the JPEGs and then have our digitization lab reimage them and we replace them later, after annotation has already happened.

**Comment by saracarl** [comment]
Possible title:  "An image and a canvas do not have to match in size"  or "Display any sized image on a canvas"

We think this recipe does not clearly convey the concept it's trying to convey, which is " image & canvas don't have to match"  An image will fill the canvas it's on, otherwise use Fragment selector.

This could also be a supplement to recipe #1.

**Comment by tomcrane** [comment]
Agree that should be linked from recipe #1.

Although this is probably quite a rare use case, it's the simplest demonstration of the Canvas abstraction. For a developer building a client, it's important to understand the Canvas as early possible, that content is being placed onto a Canvas, and that the dimensions of the Canvas are not measured in pixels. So this recipe has a teaching purpose. 

If you don't start with this understanding, you make it harder for yourself as soon as you have more than one image on the Canvas, or want to display text on the Canvas, etc.

**Comment by jrgriffiniii** [comment]
The recipe has been moved to https://github.com/IIIF/cookbook-recipes/blob/master/recipe/0004-canvas-size/index.md
