### ISSUE TITLE
ImageApiSelector - rotating/cropping an image onto a canvas

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#40]
## Reusing an image service (ImageApiSelector)
(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
I need to present rotated and cropped versions of a IIIF Image on canvases

**Comment by tomcrane** [comment]
Equivalent to 2.1 fixture

https://iiif.io/api/presentation/2.1/example/fixtures/41/manifest.json

**Comment by robcast** [comment]
For cropping see the 2.1 fixture

https://iiif.io/api/presentation/2.1/example/fixtures/36/manifest.json

**Comment by triplingual** [comment]
@kirschbombe Need link to Annex

**Comment by triplingual** [comment]
Make manifest do region and rotation, in part to distinguish from #39

**Comment by triplingual** [comment]
Good fixture: https://iiif.io/api/image/3.0/example/reference/85a96c630f077e6ac6cb984f1b752bbf-0-21198-zz00022840-1-master/full/max/0/default.jpg

**Comment by glenrobson** [comment]
focus on rotation and bring in css example.
