### ISSUE TITLE
Add navPlace viewer to relevant cookbook entries

### ISSUE THREAD

**Issue by hadro** [IIIF/cookbook-recipes#406]
Now that the [navPlace viewer](http://map.rerum.io/?iiif-content=) is out there and accepts content-state URLs, we should list it as a viewer for at least the following two recipes so folks can see the recipes work:
- [Locate a Manifest on a Web Map](https://iiif.io/api/cookbook/recipe/0154-geo-extension/)
- [Locate Multiple Canvases on a Web Map](https://iiif.io/api/cookbook/recipe/0240-navPlace-on-canvases/)

CC @glenrobson @thehabes

**Comment by thehabes** [comment]
On it

**Comment by glenrobson** [comment]
Completed in: https://github.com/IIIF/cookbook-recipes/pull/409
