### ISSUE TITLE
0047-homepage has mixed profile and type for the included ImageService3

### ISSUE THREAD

**Issue by ksclarke** [IIIF/cookbook-recipes#440]
## Recipe Name  

0047-homepage

## Use case  

It looks like the ImageService3 has a mixed profile and type (one is v3 and the other v2)? A PR fixing this is included below:

https://github.com/IIIF/cookbook-recipes/pull/439/files

**Comment by glenrobson** [comment]
Fixed in: https://github.com/IIIF/cookbook-recipes/pull/439
