### ISSUE TITLE
Bad media type for format in recipe 232?

### ISSUE THREAD

**Issue by ksclarke** [IIIF/cookbook-recipes#450]
The format media type in recipe 232's manifest-image.json currently says: "image/jpg". Shouldn't that be "image/jpeg" (which is also used in the presentation spec as an example)?

https://github.com/IIIF/cookbook-recipes/blob/a89c866ac9d989d8a78e6de59bfc9932ef2ecc51/recipe/0232-image-thumbnail-canvas/manifest-image.json#L17

https://iiif.io/api/presentation/3.0/#format

**Comment by glenrobson** [comment]
Yes I think you are right it should be image/jpeg

**Comment by glenrobson** [comment]
Note we did this before: https://github.com/IIIF/cookbook-recipes/pull/249 we should add a test to the build to stop this happening in future.
