### ISSUE TITLE
Alternative representations through rendering

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#46]
## Alternative representations through rendering

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
Show how to link to non-IIIF representations of the object, such as a PDF or 3D model.

**Comment by tomcrane** [comment]
Need to cross reference with accompanyingCanvas to explain the difference between them - 

e.g., A statue, make a manifest with one 2d canvas with a photo of the statue - gives you a "works anywhere" viable manifest for the thing. Then attach 3D model via `rendering`, clients that understand the format at the other end can follow that and show you the 3D model instead.

This isn't a job for `aoompanyingCanvas` or `placeholderCanvas` because those are not content of the object, they are optional things to show.

**Comment by triplingual** [comment]
PDF, not 3D tho
