### ISSUE TITLE
Homepage property: linking to a web page

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#47]
## Homepage

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
I want to provide a link to a web page about the object.

**Comment by glenrobson** [comment]
Homepage on the manifest.

Homepage in provider is covered by: https://iiif.io/api/cookbook/recipe/0234-provider/

**Comment by glenrobson** [comment]
Relevant part of spec: https://iiif.io/api/presentation/3.0/#homepage
