### ISSUE TITLE
Image Service for single image

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#5]
## Image Service for single image

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
Minimum viable manifest, enhanced with an image service.

**Comment by tomcrane** [comment]
Equivalent to 2.1 fixtures

https://iiif.io/api/presentation/2.1/example/fixtures/24/manifest.json
https://iiif.io/api/presentation/2.1/example/fixtures/25/manifest.json

**Comment by azaroth42** [comment]
Addition of Image API. Previous were just Presentation.

**Comment by saracarl** [comment]
Ttitle:  "[Display] Image from IIIF Image Server"

**Comment by glenrobson** [comment]
Branch in: https://github.com/IIIF/cookbook-recipes/tree/5_image_svc_single_image

**Comment by glenrobson** [comment]
I've created the following pull request so we can see what left to do:

https://github.com/IIIF/cookbook-recipes/pull/165

This is open for somebody to pick up.

**Comment by robcast** [comment]
Small issue: the second paragraph starts with "This property[...]" but the `service` property it refers to is only introduced in the third sentence of this paragraph.
