### ISSUE TITLE
Multiple languages / Internationalization 

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#6]
## Multiple values and languages

https://github.com/IIIF/cookbook-recipes/blob/master/cookbook/0006-text-language/index.md

## Use case  
If you have more than one language for descriptive properties like metadata, label, description etc. This will show single language and multiple language.

**Comment by tomcrane** [comment]
Equivalent to 2.1 fixtures

https://iiif.io/api/presentation/2.1/example/fixtures/3/manifest.json
https://iiif.io/api/presentation/2.1/example/fixtures/4/manifest.json
https://iiif.io/api/presentation/2.1/example/fixtures/6/manifest.json

**Comment by tomcrane** [comment]
This issue could also be used to make it clear that the way languages work in IIIF and the way they work in the anno model are different.

Or is that worth a separate issue to really highlight the point?

The spec currently says (in 4.4, which introduces language maps) 

> Note that this does not apply to embedded textual bodies in Annotations, which use the Web Annotation pattern of value and language as separate properties.

**Comment by mattmcgrattan** [comment]
This doesn't just apply to labels, it can also apply to other textual fields in the manifest.

**Comment by mattmcgrattan** [comment]
No reference to common search terms like Internationalisation, and doesn't make clear that there are two issues involved:

* multiple values (e.g. multiple English labels for a resource)
* multiple languages (e.g. French, English, and Japanese labels for a resource)

**Comment by mattmcgrattan** [comment]
Change to Multiple languages (Internationalism), and make a new issue for Multiple Values

**Comment by jrgriffiniii** [comment]
This recipe has been moved to https://github.com/IIIF/cookbook-recipes/blob/master/recipe/0006-text-language/index.md

**Comment by kirschbombe** [comment]
The previous recipe iteration covered both multi-value and multi-language. The cookbook team decided to break these into separate recipes: multi-value; multi-lingual; and a third for specifying region/script
