### ISSUE TITLE
An opera on one Canvas

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#64]
## An opera on one Canvas

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
Opera modelled as single extent of time

**Comment by kirschbombe** [comment]
Done or duplicate?

**Comment by glenrobson** [comment]
Table of Contents for Multiple A/V files on a Single Canvas 

https://iiif.io/api/cookbook/recipe/0064-opera-one-canvas/
