### ISSUE TITLE
An opera on multiple Canvases

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#65]
## An opera on multiple Canvases

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
Same opera as previous issue, now modelled as multiple canvases

**Comment by kirschbombe** [comment]
Isn't this one done? Or is this a duplicate ticket?

**Comment by glenrobson** [comment]
Table of Contents for Multiple A/V files on Multiple Canvases

https://iiif.io/api/cookbook/recipe/0065-opera-multiple-canvases/
