### ISSUE TITLE
Embedding HTML in descriptive properties (metadata, description)

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#7]
## Multiple formats of strings (text, html, markdown...?)

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
You want to have more control on how your metadata is displayed. For example scientific names, and also links out to other sites. Also legacy systems that might include things like italic tags.

**Comment by tomcrane** [comment]
Equivalent to 2.1 fixture

https://iiif.io/api/presentation/2.1/example/fixtures/64/manifest.json

**Comment by glenrobson** [comment]
We don't think you can use mark down. Highlight HTML

**Comment by mattmcgrattan** [comment]
Note to ensure that the implementation and description includes explicit discussion of how you tell a client that the textual value contains html, i.e. starting with an open HTML tag, e.g. <p>.
