### ISSUE TITLE
A Sammelband

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#71]
## A Sammelband

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
(What's a Sammelband? https://en.wikipedia.org/wiki/Sammelband)

**Comment by glenrobson** [comment]
Is this done by the table of contents recipe:

https://iiif.io/api/cookbook/recipe/0024-book-4-toc/ 

or the collection/manifest option in:

https://iiif.io/api/cookbook/recipe/0030-multi-volume/

**Comment by glenrobson** [comment]
Discussed in the cookbook authors call on the 14th Jan and agreed to close.
