### ISSUE TITLE
Video with captions in multiple languages

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#74]
## Video with captions in multiple languages

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
I have more than one language available for subtitles, including the language of the video itself.

**Comment by nfreire** [comment]
I volunteer to work on creating this recipe. We have an example from Europeana that can be used in the recipe.

**Comment by glenrobson** [comment]
Thanks Nuno, I've assigned you to the ticket.
