### ISSUE TITLE
Rights statement(s)

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#8]
## Rights statement(s)

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
My legal department insists that my digital objects be accompanied by certain text.

**Comment by tomcrane** [comment]
Equivalent to 2.1 fixture

https://iiif.io/api/presentation/2.1/example/fixtures/7/manifest.json

**Comment by triplingual** [comment]
I'm not seeing a separate recipe for [requiredStatement](https://iiif.io/api/presentation/3.0/#requiredstatement). It can be included in this recipe or get its own, but I'm not sufficiently well-versed to know how to make that call. On the other hand, [provider](https://iiif.io/api/presentation/3.0/#provider) doesn't have its own either, but I'm confident it doesn't belong here.
