### ISSUE TITLE
Document algorithm for determining embedded or external

### ISSUE THREAD

**Issue by azaroth42** [IIIF/cookbook-recipes#88]
Where resources can either be embedded or external references in the API, we should be consistent such that the processing algorithm to determine whether or not a client needs to retrieve the description is clear and easy to implement.

For the majority of cases, the algorithm is "does the `items` key exist in the data", and any other property is thus allowable.

**Comment by glenrobson** [comment]
Cookbook authors 4th Feb 2020. We think this is now covered in: 

https://iiif.io/api/cookbook/recipe/0269-embedded-or-referenced-annotations/
