### ISSUE TITLE
Book (simplest, > 1 canvas)

### ISSUE THREAD

**Issue by tomcrane** [IIIF/cookbook-recipes#9]
## Book (simplest, > 1 canvas)

(Provide link to `index.md` of the issue, if available. To be filled in after issue is created - you need the issue number!)

## Use case  
Simplest multi-image example

**Comment by tomcrane** [comment]
Equivalent to 2.1 fixture

https://iiif.io/api/presentation/2.1/example/fixtures/19/manifest.json

**Comment by regisrob** [comment]
FYI I've started to work on this recipe and I've pushed a first stab here: https://github.com/regisrob/cookbook-recipes/commit/ce91b00db612174d381596d9f53733978ce6d882 (but still a work in progress...).

It still lacks some comments at the end of the recipe on why the related recipes are relevant...

Moreover, I am not really satisfied at this point, I feel like it is far too long... And I wonder if there's not too much repetition compared to [recipe #1](https://github.com/regisrob/cookbook-recipes/blob/ce91b00db612174d381596d9f53733978ce6d882/recipe/0009-book-1/index.md) "Simplest Manifest - Image", by @tomcrane. I should probably refer to it for the common aspects, even though it would hinder the readability of the recipe a little bit (but maybe not...?).

- I also wonder if I should put a `summary` at the Manifest level. 
- I decided not to put `thumbnail` at all in the example Manifest, and no Image API service either. I just explain in the text the reason why it would be useful and recommended in some cases. But it may be better to have them in the Manifest (at least at Canvas level), I am not really sure... (it is not always easy to find the right balance between "simplest minimum viable" and essential best practices). What do you think?

Any feedback or advice would be highly helpful 🙏 
NB: I will be out of the office in the next few weeks, but I am happy to work again on this when I come back to work...

**Comment by azaroth42** [comment]
Intent is multiple canvases, with images.

**Comment by saracarl** [comment]
Possible new title:  "Multiple, related ordered images (Book, etc)"
